#!/bin/bash

# 快速使用指南

echo "=== 双向交流软件快速使用指南 ==="
echo ""
echo "1. 编译程序："
echo "   gcc -g -Wall -pthread -o server server.c"
echo "   gcc -g -Wall -pthread -o client client.c"
echo ""
echo "2. 启动服务器（终端1）："
echo "   ./server"
echo ""
echo "3. 启动客户端（终端2）："
echo "   ./client 127.0.0.1"
echo ""
echo "4. 启动更多客户端（终端3、4...）："
echo "   ./client 127.0.0.1"
echo ""
echo "5. 开始聊天："
echo "   - 输入用户名"
echo "   - 开始发送消息"
echo "   - 输入 'exit' 退出"
echo ""
echo "注意事项："
echo "- 先启动服务器，再启动客户端"
echo "- 每个客户端需要单独的终端窗口"
echo "- 服务器端口：8888"
echo "- 最大支持10个客户端同时在线"
echo ""
echo "项目特点："
echo "✓ TCP Socket网络通信"
echo "✓ 多线程实现双向通信"
echo "✓ 支持多客户端聊天"
echo "✓ 实时消息广播"
echo "✓ 用户进入/离开提示"
echo ""
